interface CountryCode {
  name: string;
  code: string;
  id: string; // ISO 3166-1 alpha-2 country code
}

export const countryCodes: CountryCode[] = [
  { name: 'Afghanistan', code: '+93', id: 'af' },
  { name: 'Albania', code: '+355', id: 'al' },
  { name: 'Algeria', code: '+213', id: 'dz' },
  { name: 'Andorra', code: '+376', id: 'ad' },
  { name: 'Angola', code: '+244', id: 'ao' },
  { name: 'Argentina', code: '+54', id: 'ar' },
  { name: 'Armenia', code: '+374', id: 'am' },
  { name: 'Australia', code: '+61', id: 'au' },
  { name: 'Austria', code: '+43', id: 'at' },
  { name: 'Azerbaijan', code: '+994', id: 'az' },
  { name: 'Bahrain', code: '+973', id: 'bh' },
  { name: 'Bangladesh', code: '+880', id: 'bd' },
  { name: 'Belarus', code: '+375', id: 'by' },
  { name: 'Belgium', code: '+32', id: 'be' },
  { name: 'Bhutan', code: '+975', id: 'bt' },
  { name: 'Brazil', code: '+55', id: 'br' },
  { name: 'Bulgaria', code: '+359', id: 'bg' },
  { name: 'Cambodia', code: '+855', id: 'kh' },
  { name: 'Canada', code: '+1', id: 'ca' },
  { name: 'China', code: '+86', id: 'cn' },
  { name: 'Denmark', code: '+45', id: 'dk' },
  { name: 'Egypt', code: '+20', id: 'eg' },
  { name: 'Finland', code: '+358', id: 'fi' },
  { name: 'France', code: '+33', id: 'fr' },
  { name: 'Germany', code: '+49', id: 'de' },
  { name: 'Greece', code: '+30', id: 'gr' },
  { name: 'Hong Kong', code: '+852', id: 'hk' },
  { name: 'Hungary', code: '+36', id: 'hu' },
  { name: 'Iceland', code: '+354', id: 'is' },
  { name: 'India', code: '+91', id: 'in' },
  { name: 'Indonesia', code: '+62', id: 'id' },
  { name: 'Iran', code: '+98', id: 'ir' },
  { name: 'Iraq', code: '+964', id: 'iq' },
  { name: 'Ireland', code: '+353', id: 'ie' },
  { name: 'Israel', code: '+972', id: 'il' },
  { name: 'Italy', code: '+39', id: 'it' },
  { name: 'Japan', code: '+81', id: 'jp' },
  { name: 'Jordan', code: '+962', id: 'jo' },
  { name: 'Kazakhstan', code: '+7', id: 'kz' },
  { name: 'Kenya', code: '+254', id: 'ke' },
  { name: 'Kuwait', code: '+965', id: 'kw' },
  { name: 'Kyrgyzstan', code: '+996', id: 'kg' },
  { name: 'Laos', code: '+856', id: 'la' },
  { name: 'Latvia', code: '+371', id: 'lv' },
  { name: 'Lebanon', code: '+961', id: 'lb' },
  { name: 'Libya', code: '+218', id: 'ly' },
  { name: 'Liechtenstein', code: '+423', id: 'li' },
  { name: 'Lithuania', code: '+370', id: 'lt' },
  { name: 'Luxembourg', code: '+352', id: 'lu' },
  { name: 'Macao', code: '+853', id: 'mo' },
  { name: 'Malaysia', code: '+60', id: 'my' },
  { name: 'Maldives', code: '+960', id: 'mv' },
  { name: 'Malta', code: '+356', id: 'mt' },
  { name: 'Mexico', code: '+52', id: 'mx' },
  { name: 'Monaco', code: '+377', id: 'mc' },
  { name: 'Mongolia', code: '+976', id: 'mn' },
  { name: 'Morocco', code: '+212', id: 'ma' },
  { name: 'Myanmar', code: '+95', id: 'mm' },
  { name: 'Nepal', code: '+977', id: 'np' },
  { name: 'Netherlands', code: '+31', id: 'nl' },
  { name: 'New Zealand', code: '+64', id: 'nz' },
  { name: 'Nigeria', code: '+234', id: 'ng' },
  { name: 'North Korea', code: '+850', id: 'kp' },
  { name: 'Norway', code: '+47', id: 'no' },
  { name: 'Oman', code: '+968', id: 'om' },
  { name: 'Pakistan', code: '+92', id: 'pk' },
  { name: 'Palestine', code: '+970', id: 'ps' },
  { name: 'Panama', code: '+507', id: 'pa' },
  { name: 'Philippines', code: '+63', id: 'ph' },
  { name: 'Poland', code: '+48', id: 'pl' },
  { name: 'Portugal', code: '+351', id: 'pt' },
  { name: 'Qatar', code: '+974', id: 'qa' },
  { name: 'Romania', code: '+40', id: 'ro' },
  { name: 'Russia', code: '+7', id: 'ru' },
  { name: 'Saudi Arabia', code: '+966', id: 'sa' },
  { name: 'Serbia', code: '+381', id: 'rs' },
  { name: 'Singapore', code: '+65', id: 'sg' },
  { name: 'Slovakia', code: '+421', id: 'sk' },
  { name: 'Slovenia', code: '+386', id: 'si' },
  { name: 'South Africa', code: '+27', id: 'za' },
  { name: 'South Korea', code: '+82', id: 'kr' },
  { name: 'Spain', code: '+34', id: 'es' },
  { name: 'Sri Lanka', code: '+94', id: 'lk' },
  { name: 'Sweden', code: '+46', id: 'se' },
  { name: 'Switzerland', code: '+41', id: 'ch' },
  { name: 'Syria', code: '+963', id: 'sy' },
  { name: 'Taiwan', code: '+886', id: 'tw' },
  { name: 'Thailand', code: '+66', id: 'th' },
  { name: 'Turkey', code: '+90', id: 'tr' },
  { name: 'Ukraine', code: '+380', id: 'ua' },
  { name: 'United Arab Emirates', code: '+971', id: 'ae' },
  { name: 'United Kingdom', code: '+44', id: 'gb' },
  { name: 'United States', code: '+1', id: 'us' },
  { name: 'Uzbekistan', code: '+998', id: 'uz' },
  { name: 'Vatican City', code: '+379', id: 'va' },
  { name: 'Vietnam', code: '+84', id: 'vn' },
  { name: 'Yemen', code: '+967', id: 'ye' },
].sort((a, b) => a.name.localeCompare(b.name));